# Generated by Django 2.1 on 2018-08-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('like', models.CharField(max_length=32)),
                ('eat', models.CharField(max_length=32)),
            ],
        ),
    ]
