# Generated by Django 2.0.6 on 2018-08-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peppa', '0003_auto_20180809_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='branchname',
            field=models.CharField(default='default', max_length=50, verbose_name='分支名称'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='tags',
            field=models.CharField(max_length=50, verbose_name='标签'),
        ),
    ]
