# Generated by Django 2.0.6 on 2018-09-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peppa', '0007_auto_20180903_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='consul_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50, verbose_name='项目')),
                ('consul_url', models.CharField(max_length=100, verbose_name='consul路径')),
                ('consul_env', models.CharField(max_length=30, verbose_name='环境')),
                ('consul_version', models.CharField(max_length=80, verbose_name='版本')),
            ],
            options={
                'db_table': 'consul_project',
            },
        ),
    ]
