# Generated by Django 2.0.6 on 2018-09-03 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peppa', '0008_consul_project'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consul_project',
            table=None,
        ),
    ]
