# Generated by Django 2.0.6 on 2018-09-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peppa', '0009_auto_20180903_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='consul_version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50, verbose_name='项目')),
                ('consul_version', models.CharField(max_length=80, verbose_name='版本')),
                ('consul_key', models.CharField(max_length=100, verbose_name='key值')),
                ('consul_values', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='consul_project',
            name='consul_version',
        ),
    ]
