# Generated by Django 2.0.6 on 2018-08-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peppa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='applyEnv',
            field=models.CharField(default='0', max_length=40, verbose_name='环境'),
        ),
        migrations.AddField(
            model_name='projecttomachine',
            name='applyEnv',
            field=models.CharField(default='0', max_length=40, verbose_name='环境'),
        ),
    ]
