# Generated by Django 2.0.6 on 2018-08-12 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peppa', '0004_auto_20180810_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='applyEnv',
        ),
    ]
