# Generated by Django 2.0.6 on 2018-08-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peppa', '0005_remove_apply_applyenv'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='applyEnv',
            field=models.CharField(default='0', max_length=40, verbose_name='环境'),
        ),
    ]
