# Generated by Django 2.0.6 on 2018-09-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peppa', '0010_auto_20180905_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consul_version',
            name='consul_key',
            field=models.TextField(),
        ),
    ]
