# Generated by Django 2.0.6 on 2018-09-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peppa', '0011_auto_20180905_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='consul_version',
            name='consul_env',
            field=models.CharField(default='test', max_length=30, verbose_name='环境'),
        ),
    ]
